### ISSUE TITLE
TODO list 17th Feb

### ISSUE THREAD

**Issue by prototriangle** [CreatEDHack/2018#4]
- [x] put cameron's email for sponsorship
- [x] change colours of logo to match poster
- [x] add venue details and a map
- [x] improve faq
- [x] improve "about" information at top of page
- [x] section on what is a hardware hack, specifically
- [x] remove unconfirmed sponsor logos
- [x] use ordering: 
```
Logo
date & location
---
Short description
Buttons
---
Hardware emphasis
---
Schedule
---
FAQs
---
Venue details + map
---
Sponsors
---
Footer
```

**Comment by prototriangle** [comment]
Did not finish. Confused why I merged

**Comment by prototriangle** [comment]
Will be closed by https://github.com/CreatEDHack/createdhack.github.io/pull/20
